
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnPizza = new javax.swing.JButton();
        jbtnWagyu = new javax.swing.JButton();
        jbtnEspresso = new javax.swing.JButton();
        jbtnbeefburger = new javax.swing.JButton();
        jbtnramen = new javax.swing.JButton();
        jbtnsalmon = new javax.swing.JButton();
        jbtnRainbow = new javax.swing.JButton();
        jbtnkebab = new javax.swing.JButton();
        jbtnpancake = new javax.swing.JButton();
        jbtngrapesky = new javax.swing.JButton();
        jbtnsushi = new javax.swing.JButton();
        jbtnbluelagoon = new javax.swing.JButton();
        jbtntaichan = new javax.swing.JButton();
        jbtnlatte = new javax.swing.JButton();
        jbtngelato = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPay = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jbtnPay = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jtxtBarcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPizza.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pizza.jpg"))); // NOI18N
        jbtnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 150));

        jbtnWagyu.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnWagyu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/WagyuA6.jpg"))); // NOI18N
        jbtnWagyu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWagyuActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnWagyu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 150));

        jbtnEspresso.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnEspresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Espresso.jpg"))); // NOI18N
        jbtnEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEspressoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 150));

        jbtnbeefburger.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnbeefburger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BurgerBeef.jpg"))); // NOI18N
        jbtnbeefburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbeefburgerActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbeefburger, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 130, 150));

        jbtnramen.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnramen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CurryChickenRamen.jpg"))); // NOI18N
        jbtnramen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnramenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnramen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 130, 150));

        jbtnsalmon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnsalmon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Salmon.jpg"))); // NOI18N
        jbtnsalmon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsalmonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsalmon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, 140));

        jbtnRainbow.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnRainbow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Rainbow.jpg"))); // NOI18N
        jbtnRainbow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRainbowActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRainbow, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 130, 140));

        jbtnkebab.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnkebab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KebabSapi.jpg"))); // NOI18N
        jbtnkebab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnkebabActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnkebab, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 130, 140));

        jbtnpancake.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnpancake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BluStraw Pancake .jpg"))); // NOI18N
        jbtnpancake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpancakeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnpancake, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 130, 140));

        jbtngrapesky.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtngrapesky.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gepsy.jpg"))); // NOI18N
        jbtngrapesky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngrapeskyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtngrapesky, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 130, 140));

        jbtnsushi.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnsushi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Sushi.jpg"))); // NOI18N
        jbtnsushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsushiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnsushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 140));

        jbtnbluelagoon.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnbluelagoon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/BlueLagoonCoocktail.jpg"))); // NOI18N
        jbtnbluelagoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbluelagoonActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnbluelagoon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 130, 140));

        jbtntaichan.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtntaichan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Taichan.jpg"))); // NOI18N
        jbtntaichan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntaichanActionPerformed(evt);
            }
        });
        jPanel1.add(jbtntaichan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 130, 140));

        jbtnlatte.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnlatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kopps.jpg"))); // NOI18N
        jbtnlatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlatteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnlatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 130, 140));

        jbtngelato.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtngelato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gelato.jpg"))); // NOI18N
        jbtngelato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtngelatoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtngelato, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 130, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 710, 490));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 110));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 110));

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 110));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 90, 110));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, 110));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 90, 110));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 90, 110));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 90, 110));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, 110));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 110));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton11.setText(".");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, 110));

        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 90, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 320, 410));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jPanel4.setBackground(new java.awt.Color(51, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tax");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total");

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        jPanel6.setBackground(new java.awt.Color(51, 153, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Payment");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cash");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Change");

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });

        jcboPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Visa" }));
        jcboPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jcboPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jtxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcboPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)))
                .addGap(40, 40, 40))
        );

        jPanel5.setBackground(new java.awt.Color(51, 153, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(62, 62, 62))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPay)
                    .addComponent(jbtnReset))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrint)
                    .addComponent(jbtnRemove))
                .addGap(18, 18, 18)
                .addComponent(jbtnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1380, 250));

        jtxtBarcode.setFont(new java.awt.Font("Code39", 1, 24)); // NOI18N
        getContentPane().add(jtxtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 320, 80));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Aldy's Cashier");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 140, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//======================================================Function======================================
    
     public void ItemCost()
     {
         double sum = 0;
         
         for (int i = 0; i < jTable1.getRowCount(); i++)
         {
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
         }
         jtxtSubTotal.setText(Double.toString(sum));
         double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
         
         Double cTax = (cTotal1 * 3.9)/100;
         String iTaxTotal = String.format("Rp %.2f", cTax);
         jtxtTax.setText(iTaxTotal);
         
         String iSubTotal = String.format("Rp %.2f", cTotal1);
         jtxtSubTotal.setText(iSubTotal);
         
         String iTotal = String.format("Rp %.2f", cTotal1 + cTax);
         jtxtTotal.setText(iTotal);
         
         String BarCode = String.format("Total is %.2f", cTotal1 + cTax);
         jtxtBarcode.setText(BarCode);
     }
     
     //======================================================Function Changer======================================
    
     public void Change()
     {
         double sum =0;
         double tax =3.9;
         double cash = Double.parseDouble(jtxtDisplay.getText());
         
         for (int i = 0; i < jTable1.getRowCount(); i++)
         {
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
         }
         
         double cTax = (sum * 3.9)/100;
         double cChange = (cash - (sum + cTax));
         
         String ChangeGiven = String.format("Rp %.2f",cChange); 
         jtxtChange.setText(ChangeGiven);
     }
    
    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn7.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn7.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn8.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn8.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn9.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn9.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn4.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn4.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn5.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn5.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn6.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn6.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn1.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn1.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn2.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn2.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn3.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn3.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        
        String Enternumber = jtxtDisplay.getText();
        
        if (Enternumber == "")
        {
          jtxtDisplay.setText(jbtn0.getText()); 
        }
        else
        {
           Enternumber = jtxtDisplay.getText() + jbtn0.getText();
           jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        // TODO add your handling code here:
        
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
        if(! jtxtDisplay.getText().contains("."))
        {
           jtxtDisplay.setText(jtxtDisplay.getText() + jButton11.getText()); 
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jbtnWagyuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWagyuActionPerformed
        // TODO add your handling code here:
        double PriceOfItem = 450000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"WagyuA6","1",PriceOfItem});
        ItemCost();
        
    }//GEN-LAST:event_jbtnWagyuActionPerformed

    private void jbtnRainbowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRainbowActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 45000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rainbow Mocktail","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnRainbowActionPerformed

    private void jbtnkebabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnkebabActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 27000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Kebab","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnkebabActionPerformed

    private void jbtnEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEspressoActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 18000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Espresso Coffee","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnEspressoActionPerformed

    private void jbtnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPizzaActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 99000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Medium CheesBeef Pizza","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPizzaActionPerformed

    private void jbtnbeefburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbeefburgerActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 32000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Beef Burger","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnbeefburgerActionPerformed

    private void jbtnramenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnramenActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 65000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Curry Ramen","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnramenActionPerformed

    private void jbtnsalmonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsalmonActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 125000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Salmon Sashimi","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnsalmonActionPerformed

    private void jbtnpancakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpancakeActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 96000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"BluStraw Pancake","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnpancakeActionPerformed

    private void jbtngrapeskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngrapeskyActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 25000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"GrapeSky Cocktail","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtngrapeskyActionPerformed

    private void jbtnsushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsushiActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 100000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sushi Tei","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnsushiActionPerformed

    private void jbtnbluelagoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbluelagoonActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 33000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Blue Lagoon","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnbluelagoonActionPerformed

    private void jbtntaichanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntaichanActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 35000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sate Taichan","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtntaichanActionPerformed

    private void jbtngelatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtngelatoActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 55000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Gelato Ice Cream","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtngelatoActionPerformed

    private void jbtnlatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlatteActionPerformed
        // TODO add your handling code here:
        
        double PriceOfItem = 22000;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Caffe Latte","1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnlatteActionPerformed

    private void jcboPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcboPayActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        // TODO add your handling code here:
        
        if (jcboPay.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarcode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
                {
                    System.err.format("No Printer Found", e.getMessage());
                }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if( RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        
        ItemCost();
        
        if (jcboPay.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnEspresso;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPizza;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRainbow;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnWagyu;
    private javax.swing.JButton jbtnbeefburger;
    private javax.swing.JButton jbtnbluelagoon;
    private javax.swing.JButton jbtngelato;
    private javax.swing.JButton jbtngrapesky;
    private javax.swing.JButton jbtnkebab;
    private javax.swing.JButton jbtnlatte;
    private javax.swing.JButton jbtnpancake;
    private javax.swing.JButton jbtnramen;
    private javax.swing.JButton jbtnsalmon;
    private javax.swing.JButton jbtnsushi;
    private javax.swing.JButton jbtntaichan;
    private javax.swing.JComboBox<String> jcboPay;
    private javax.swing.JTextField jtxtBarcode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
